stages:
  - prepare

process:template:
  stage: prepare
  before_script:
    - apk add --no-cache gettext jq
  script:
    - CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
    - export PROJECTS=$(echo "$CHANGED_FILES" | sed -n 's#^\([^/]*\)/compose\.yaml#\1#p' | jq -R -s -c 'split("\n")[:-1]')
    - if [ "$PROJECTS" = "[]" ]; then
        echo "No projects found to deploy";
        printf "dummy:\n  script:\n    - echo \"Job succeeded\"\n" > template.gitlab-ci.yml;
      else
        echo "Found stacks $PROJECTS";
        envsubst '${PROJECTS}' < template.yml > template.gitlab-ci.yml;
      fi
  artifacts:
    paths:
      - template.gitlab-ci.yml
    expire_in: 1 hour

trigger:template:
  stage: prepare
  trigger:
    include:
      - artifact: template.gitlab-ci.yml
        job: process:template
    forward:
      pipeline_variables: true
  needs: ["process:template"]
