# template.yml
stages:
  - matrix

deploy:stacks:
  stage: matrix
  image: alpine:latest  
  parallel:
    matrix:
      - STACK_NAME: ${PROJECTS}
  before_script:
    - apk add --no-cache curl jq
    - chmod +x ./deploy-stack.sh
  script:
    - source deploy-stack.sh